### ISSUE TITLE
Consider allowing stylesheets to be embedded with <link> as well as @import

### ISSUE THREAD

**Issue by faceless2** [pdf-association/Deriving-HTML-from-PDF#26]
Currently Associated Files that are `text/css` **must** be embedded in the final HTML using an `@import` statement.

Could we consider allowing these to be embedded with `<link>` as well? The end result is the same but `<link>` has two advantages:

1. `<link>` can accept a `title` attribute which can be mapped to the description of the associated file, if specified. This could give stylesheets some context.
2. `<link>` can take a charset attribute, which is [deprecated](https://html.spec.whatwg.org/multipage/obsolete.html#attr-link-charset[deprecated), yes, but if the derivation code is saving the stylesheets to local storage and referencing them via a `file://` URL, then it's the only way to set the encoding for a stylesheet that needs it - for example, if the original stylesheet has no BOM, no `@charset` and was served with `Content-Type: text/css;charset=Shift-JIS`.  If this were the case, then if using `@import` the stylesheet would need to be re-encoded to UTF8 before embedding.

I realise these are pretty weak arguments, but I'm raising them because the last one is a bit of an obscure edge case and might not have been considered when `@import` was chosen and not `<link>`. Perhaps allowing both might allow more flexibility?

**Comment by chris-bfo** [comment]
Please could we also consider allowing them just to be included directly as the text content of a style element? The advantages of being able to deal with a single file have been extensively documented as part of the PDF format movement. We should allow the derivation process to be able to create standalone HTML or XHTML documents wherever feasible. That could be achieved by using a link element with a data: URL, but it would be a lot more readable as a style element.

**Comment by romantoda** [comment]
Proposal is to allow
for css: using link, using style with import or using style with direct content of AF
for javascript: using script with src or direct content
for images and svg: using teh URL constructed with data

**Comment by romantoda** [comment]
TWG agrees
