### ISSUE TITLE
fix TextPosition attributes 

### ISSUE THREAD

**Issue by romantoda** [pdf-association/Deriving-HTML-from-PDF#39]
The TextPosition attribute can change the html tag, but the behavior is unwanted in certain scenarios (on Link structure element)

**Comment by ozross** [comment]
@romantoda Not sure just what you mean. Example please?
See my comment to issue [#30](https://github.com/pdf-association/Deriving-HTML-from-PDF/issues/30).
It has links on raised footnote markers.

**Comment by romantoda** [comment]
TextPosition attribute can be present on any ILSE or BLSE containing ILSE or direct content. As I read it, the TextPosition is applied to the content itself not the SE
We don’t distinguish what type of content (could be image, paths too)
It could technically be on  ``` <Link>, <H> even <Caption> ```  
Proposed solution is to keep original derived html tag and always add additional *<sup>* or *<sub>* as a direct child *<sub>* can contain *<img>* too
Examples:
```  
<Link TextPosition> { text } → <a href><sup>text</sup></a> 
<P TextPosition> { text } → <p> <sup> text </sup> </p>
<H1> {<Lbl TextPosition> {1} Chapter}  → <h1><label><sup>1</sup></label>Chapter</h1>
```

**Comment by romantoda** [comment]
TWG agreed
